// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/node_api.proto

package nodeapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Line is an operator-entered quantity before unit conversion: the uom may be the
// item's base unit or any of its declared alternates.
type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	LotId         string                 `protobuf:"bytes,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	Qty           float64                `protobuf:"fixed64,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Uom           string                 `protobuf:"bytes,4,opt,name=uom,proto3" json:"uom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_proto_node_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{0}
}

func (x *Line) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Line) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *Line) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Line) GetUom() string {
	if x != nil {
		return x.Uom
	}
	return ""
}

// CommandResponse returns the identities of the events the command appended, in
// order. An empty list is impossible: a command either appends or fails.
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventIds      []string               `protobuf:"bytes,1,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_node_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type ReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptId     string                 `protobuf:"bytes,1,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	DeliveryNote  string                 `protobuf:"bytes,2,opt,name=delivery_note,json=deliveryNote,proto3" json:"delivery_note,omitempty"`
	PoRef         string                 `protobuf:"bytes,3,opt,name=po_ref,json=poRef,proto3" json:"po_ref,omitempty"`
	Line          *Line                  `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_proto_node_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{2}
}

func (x *ReceiveRequest) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *ReceiveRequest) GetDeliveryNote() string {
	if x != nil {
		return x.DeliveryNote
	}
	return ""
}

func (x *ReceiveRequest) GetPoRef() string {
	if x != nil {
		return x.PoRef
	}
	return ""
}

func (x *ReceiveRequest) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *ReceiveRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type PutAwayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          *Line                  `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAwayRequest) Reset() {
	*x = PutAwayRequest{}
	mi := &file_proto_node_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAwayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAwayRequest) ProtoMessage() {}

func (x *PutAwayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAwayRequest.ProtoReflect.Descriptor instead.
func (*PutAwayRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{3}
}

func (x *PutAwayRequest) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *PutAwayRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PutAwayRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type PickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          *Line                  `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	OrderRef      string                 `protobuf:"bytes,3,opt,name=order_ref,json=orderRef,proto3" json:"order_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickRequest) Reset() {
	*x = PickRequest{}
	mi := &file_proto_node_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickRequest) ProtoMessage() {}

func (x *PickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickRequest.ProtoReflect.Descriptor instead.
func (*PickRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{4}
}

func (x *PickRequest) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *PickRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PickRequest) GetOrderRef() string {
	if x != nil {
		return x.OrderRef
	}
	return ""
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Line          *Line                  `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_proto_node_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveRequest) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *ReserveRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_proto_node_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type StartCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountId       string                 `protobuf:"bytes,1,opt,name=count_id,json=countId,proto3" json:"count_id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCountRequest) Reset() {
	*x = StartCountRequest{}
	mi := &file_proto_node_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCountRequest) ProtoMessage() {}

func (x *StartCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCountRequest.ProtoReflect.Descriptor instead.
func (*StartCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{7}
}

func (x *StartCountRequest) GetCountId() string {
	if x != nil {
		return x.CountId
	}
	return ""
}

func (x *StartCountRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CountLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountId       string                 `protobuf:"bytes,1,opt,name=count_id,json=countId,proto3" json:"count_id,omitempty"`
	Line          *Line                  `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountLineRequest) Reset() {
	*x = CountLineRequest{}
	mi := &file_proto_node_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountLineRequest) ProtoMessage() {}

func (x *CountLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountLineRequest.ProtoReflect.Descriptor instead.
func (*CountLineRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{8}
}

func (x *CountLineRequest) GetCountId() string {
	if x != nil {
		return x.CountId
	}
	return ""
}

func (x *CountLineRequest) GetLine() *Line {
	if x != nil {
		return x.Line
	}
	return nil
}

type CloseCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountId       string                 `protobuf:"bytes,1,opt,name=count_id,json=countId,proto3" json:"count_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseCountRequest) Reset() {
	*x = CloseCountRequest{}
	mi := &file_proto_node_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseCountRequest) ProtoMessage() {}

func (x *CloseCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseCountRequest.ProtoReflect.Descriptor instead.
func (*CloseCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{9}
}

func (x *CloseCountRequest) GetCountId() string {
	if x != nil {
		return x.CountId
	}
	return ""
}

type DispatchTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Lines         []*Line                `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTransferRequest) Reset() {
	*x = DispatchTransferRequest{}
	mi := &file_proto_node_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTransferRequest) ProtoMessage() {}

func (x *DispatchTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTransferRequest.ProtoReflect.Descriptor instead.
func (*DispatchTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{10}
}

func (x *DispatchTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *DispatchTransferRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *DispatchTransferRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DispatchTransferRequest) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ReceiveTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Lines         []*Line                `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveTransferRequest) Reset() {
	*x = ReceiveTransferRequest{}
	mi := &file_proto_node_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveTransferRequest) ProtoMessage() {}

func (x *ReceiveTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveTransferRequest.ProtoReflect.Descriptor instead.
func (*ReceiveTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{11}
}

func (x *ReceiveTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ReceiveTransferRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ReceiveTransferRequest) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

type StockOnHandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockOnHandRequest) Reset() {
	*x = StockOnHandRequest{}
	mi := &file_proto_node_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockOnHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockOnHandRequest) ProtoMessage() {}

func (x *StockOnHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockOnHandRequest.ProtoReflect.Descriptor instead.
func (*StockOnHandRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{12}
}

func (x *StockOnHandRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *StockOnHandRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type StockRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	LotId         string                 `protobuf:"bytes,3,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	Qty           float64                `protobuf:"fixed64,4,opt,name=qty,proto3" json:"qty,omitempty"`
	Available     float64                `protobuf:"fixed64,5,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockRow) Reset() {
	*x = StockRow{}
	mi := &file_proto_node_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRow) ProtoMessage() {}

func (x *StockRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRow.ProtoReflect.Descriptor instead.
func (*StockRow) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{13}
}

func (x *StockRow) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *StockRow) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *StockRow) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *StockRow) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *StockRow) GetAvailable() float64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type StockOnHandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*StockRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockOnHandResponse) Reset() {
	*x = StockOnHandResponse{}
	mi := &file_proto_node_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockOnHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockOnHandResponse) ProtoMessage() {}

func (x *StockOnHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockOnHandResponse.ProtoReflect.Descriptor instead.
func (*StockOnHandResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{14}
}

func (x *StockOnHandResponse) GetRows() []*StockRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ExceptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExceptionsRequest) Reset() {
	*x = ExceptionsRequest{}
	mi := &file_proto_node_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExceptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionsRequest) ProtoMessage() {}

func (x *ExceptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionsRequest.ProtoReflect.Descriptor instead.
func (*ExceptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{15}
}

// ExceptionRow is one thing central reversed, or one balance a compensation drove
// negative. resolved is false while it still needs a human.
type ExceptionRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CausedBy      string                 `protobuf:"bytes,4,opt,name=caused_by,json=causedBy,proto3" json:"caused_by,omitempty"`
	Sku           string                 `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	LotId         string                 `protobuf:"bytes,7,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	Qty           float64                `protobuf:"fixed64,8,opt,name=qty,proto3" json:"qty,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	Resolved      bool                   `protobuf:"varint,10,opt,name=resolved,proto3" json:"resolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExceptionRow) Reset() {
	*x = ExceptionRow{}
	mi := &file_proto_node_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExceptionRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionRow) ProtoMessage() {}

func (x *ExceptionRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionRow.ProtoReflect.Descriptor instead.
func (*ExceptionRow) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{16}
}

func (x *ExceptionRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExceptionRow) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExceptionRow) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ExceptionRow) GetCausedBy() string {
	if x != nil {
		return x.CausedBy
	}
	return ""
}

func (x *ExceptionRow) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ExceptionRow) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ExceptionRow) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *ExceptionRow) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *ExceptionRow) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *ExceptionRow) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

type ExceptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*ExceptionRow        `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExceptionsResponse) Reset() {
	*x = ExceptionsResponse{}
	mi := &file_proto_node_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExceptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionsResponse) ProtoMessage() {}

func (x *ExceptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionsResponse.ProtoReflect.Descriptor instead.
func (*ExceptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{17}
}

func (x *ExceptionsResponse) GetRows() []*ExceptionRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type TransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransfersRequest) Reset() {
	*x = TransfersRequest{}
	mi := &file_proto_node_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransfersRequest) ProtoMessage() {}

func (x *TransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransfersRequest.ProtoReflect.Descriptor instead.
func (*TransfersRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{18}
}

type TransferRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromNode      string                 `protobuf:"bytes,2,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,3,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Dispatched    float64                `protobuf:"fixed64,4,opt,name=dispatched,proto3" json:"dispatched,omitempty"`
	Received      float64                `protobuf:"fixed64,5,opt,name=received,proto3" json:"received,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	DispatchedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=dispatched_at,json=dispatchedAt,proto3" json:"dispatched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRow) Reset() {
	*x = TransferRow{}
	mi := &file_proto_node_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRow) ProtoMessage() {}

func (x *TransferRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRow.ProtoReflect.Descriptor instead.
func (*TransferRow) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{19}
}

func (x *TransferRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferRow) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *TransferRow) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *TransferRow) GetDispatched() float64 {
	if x != nil {
		return x.Dispatched
	}
	return 0
}

func (x *TransferRow) GetReceived() float64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *TransferRow) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferRow) GetDispatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DispatchedAt
	}
	return nil
}

type TransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TransferRow         `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransfersResponse) Reset() {
	*x = TransfersResponse{}
	mi := &file_proto_node_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransfersResponse) ProtoMessage() {}

func (x *TransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransfersResponse.ProtoReflect.Descriptor instead.
func (*TransfersResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_api_proto_rawDescGZIP(), []int{20}
}

func (x *TransfersResponse) GetRows() []*TransferRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_proto_node_api_proto protoreflect.FileDescriptor

const file_proto_node_api_proto_rawDesc = "" +
	"\n" +
	"\x14proto/node_api.proto\x12\x11warehouse.node.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\x04Line\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x15\n" +
	"\x06lot_id\x18\x02 \x01(\tR\x05lotId\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x01R\x03qty\x12\x10\n" +
	"\x03uom\x18\x04 \x01(\tR\x03uom\".\n" +
	"\x0fCommandResponse\x12\x1b\n" +
	"\tevent_ids\x18\x01 \x03(\tR\beventIds\"\xa8\x01\n" +
	"\x0eReceiveRequest\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x01 \x01(\tR\treceiptId\x12#\n" +
	"\rdelivery_note\x18\x02 \x01(\tR\fdeliveryNote\x12\x15\n" +
	"\x06po_ref\x18\x03 \x01(\tR\x05poRef\x12+\n" +
	"\x04line\x18\x04 \x01(\v2\x17.warehouse.node.v1.LineR\x04line\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"a\n" +
	"\x0ePutAwayRequest\x12+\n" +
	"\x04line\x18\x01 \x01(\v2\x17.warehouse.node.v1.LineR\x04line\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"k\n" +
	"\vPickRequest\x12+\n" +
	"\x04line\x18\x01 \x01(\v2\x17.warehouse.node.v1.LineR\x04line\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x1b\n" +
	"\torder_ref\x18\x03 \x01(\tR\borderRef\"\x80\x01\n" +
	"\x0eReserveRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12+\n" +
	"\x04line\x18\x02 \x01(\v2\x17.warehouse.node.v1.LineR\x04line\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"B\n" +
	"\x19ReleaseReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"J\n" +
	"\x11StartCountRequest\x12\x19\n" +
	"\bcount_id\x18\x01 \x01(\tR\acountId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"Z\n" +
	"\x10CountLineRequest\x12\x19\n" +
	"\bcount_id\x18\x01 \x01(\tR\acountId\x12+\n" +
	"\x04line\x18\x02 \x01(\v2\x17.warehouse.node.v1.LineR\x04line\".\n" +
	"\x11CloseCountRequest\x12\x19\n" +
	"\bcount_id\x18\x01 \x01(\tR\acountId\"\x96\x01\n" +
	"\x17DispatchTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12-\n" +
	"\x05lines\x18\x04 \x03(\v2\x17.warehouse.node.v1.LineR\x05lines\"x\n" +
	"\x16ReceiveTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12-\n" +
	"\x05lines\x18\x03 \x03(\v2\x17.warehouse.node.v1.LineR\x05lines\"B\n" +
	"\x12StockOnHandRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\x7f\n" +
	"\bStockRow\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x15\n" +
	"\x06lot_id\x18\x03 \x01(\tR\x05lotId\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x01R\x03qty\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\x01R\tavailable\"F\n" +
	"\x13StockOnHandResponse\x12/\n" +
	"\x04rows\x18\x01 \x03(\v2\x1b.warehouse.node.v1.StockRowR\x04rows\"\x13\n" +
	"\x11ExceptionsRequest\"\x97\x02\n" +
	"\fExceptionRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1b\n" +
	"\tcaused_by\x18\x04 \x01(\tR\bcausedBy\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x15\n" +
	"\x06lot_id\x18\a \x01(\tR\x05lotId\x12\x10\n" +
	"\x03qty\x18\b \x01(\x01R\x03qty\x12;\n" +
	"\vrecorded_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\x12\x1a\n" +
	"\bresolved\x18\n" +
	" \x01(\bR\bresolved\"I\n" +
	"\x12ExceptionsResponse\x123\n" +
	"\x04rows\x18\x01 \x03(\v2\x1f.warehouse.node.v1.ExceptionRowR\x04rows\"\x12\n" +
	"\x10TransfersRequest\"\xe8\x01\n" +
	"\vTransferRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfrom_node\x18\x02 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x03 \x01(\tR\x06toNode\x12\x1e\n" +
	"\n" +
	"dispatched\x18\x04 \x01(\x01R\n" +
	"dispatched\x12\x1a\n" +
	"\breceived\x18\x05 \x01(\x01R\breceived\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12?\n" +
	"\rdispatched_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fdispatchedAt\"G\n" +
	"\x11TransfersResponse\x122\n" +
	"\x04rows\x18\x01 \x03(\v2\x1e.warehouse.node.v1.TransferRowR\x04rows2\x90\t\n" +
	"\aNodeAPI\x12P\n" +
	"\aReceive\x12!.warehouse.node.v1.ReceiveRequest\x1a\".warehouse.node.v1.CommandResponse\x12P\n" +
	"\aPutAway\x12!.warehouse.node.v1.PutAwayRequest\x1a\".warehouse.node.v1.CommandResponse\x12J\n" +
	"\x04Pick\x12\x1e.warehouse.node.v1.PickRequest\x1a\".warehouse.node.v1.CommandResponse\x12P\n" +
	"\aReserve\x12!.warehouse.node.v1.ReserveRequest\x1a\".warehouse.node.v1.CommandResponse\x12f\n" +
	"\x12ReleaseReservation\x12,.warehouse.node.v1.ReleaseReservationRequest\x1a\".warehouse.node.v1.CommandResponse\x12V\n" +
	"\n" +
	"StartCount\x12$.warehouse.node.v1.StartCountRequest\x1a\".warehouse.node.v1.CommandResponse\x12T\n" +
	"\tCountLine\x12#.warehouse.node.v1.CountLineRequest\x1a\".warehouse.node.v1.CommandResponse\x12V\n" +
	"\n" +
	"CloseCount\x12$.warehouse.node.v1.CloseCountRequest\x1a\".warehouse.node.v1.CommandResponse\x12b\n" +
	"\x10DispatchTransfer\x12*.warehouse.node.v1.DispatchTransferRequest\x1a\".warehouse.node.v1.CommandResponse\x12`\n" +
	"\x0fReceiveTransfer\x12).warehouse.node.v1.ReceiveTransferRequest\x1a\".warehouse.node.v1.CommandResponse\x12\\\n" +
	"\vStockOnHand\x12%.warehouse.node.v1.StockOnHandRequest\x1a&.warehouse.node.v1.StockOnHandResponse\x12Y\n" +
	"\n" +
	"Exceptions\x12$.warehouse.node.v1.ExceptionsRequest\x1a%.warehouse.node.v1.ExceptionsResponse\x12V\n" +
	"\tTransfers\x12#.warehouse.node.v1.TransfersRequest\x1a$.warehouse.node.v1.TransfersResponseBVZTgithub.com/dhiazfathra/local-first-architecture/warehouse-node/proto/nodeapi;nodeapib\x06proto3"

var (
	file_proto_node_api_proto_rawDescOnce sync.Once
	file_proto_node_api_proto_rawDescData []byte
)

func file_proto_node_api_proto_rawDescGZIP() []byte {
	file_proto_node_api_proto_rawDescOnce.Do(func() {
		file_proto_node_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_api_proto_rawDesc), len(file_proto_node_api_proto_rawDesc)))
	})
	return file_proto_node_api_proto_rawDescData
}

var file_proto_node_api_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_node_api_proto_goTypes = []any{
	(*Line)(nil),                      // 0: warehouse.node.v1.Line
	(*CommandResponse)(nil),           // 1: warehouse.node.v1.CommandResponse
	(*ReceiveRequest)(nil),            // 2: warehouse.node.v1.ReceiveRequest
	(*PutAwayRequest)(nil),            // 3: warehouse.node.v1.PutAwayRequest
	(*PickRequest)(nil),               // 4: warehouse.node.v1.PickRequest
	(*ReserveRequest)(nil),            // 5: warehouse.node.v1.ReserveRequest
	(*ReleaseReservationRequest)(nil), // 6: warehouse.node.v1.ReleaseReservationRequest
	(*StartCountRequest)(nil),         // 7: warehouse.node.v1.StartCountRequest
	(*CountLineRequest)(nil),          // 8: warehouse.node.v1.CountLineRequest
	(*CloseCountRequest)(nil),         // 9: warehouse.node.v1.CloseCountRequest
	(*DispatchTransferRequest)(nil),   // 10: warehouse.node.v1.DispatchTransferRequest
	(*ReceiveTransferRequest)(nil),    // 11: warehouse.node.v1.ReceiveTransferRequest
	(*StockOnHandRequest)(nil),        // 12: warehouse.node.v1.StockOnHandRequest
	(*StockRow)(nil),                  // 13: warehouse.node.v1.StockRow
	(*StockOnHandResponse)(nil),       // 14: warehouse.node.v1.StockOnHandResponse
	(*ExceptionsRequest)(nil),         // 15: warehouse.node.v1.ExceptionsRequest
	(*ExceptionRow)(nil),              // 16: warehouse.node.v1.ExceptionRow
	(*ExceptionsResponse)(nil),        // 17: warehouse.node.v1.ExceptionsResponse
	(*TransfersRequest)(nil),          // 18: warehouse.node.v1.TransfersRequest
	(*TransferRow)(nil),               // 19: warehouse.node.v1.TransferRow
	(*TransfersResponse)(nil),         // 20: warehouse.node.v1.TransfersResponse
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_proto_node_api_proto_depIdxs = []int32{
	0,  // 0: warehouse.node.v1.ReceiveRequest.line:type_name -> warehouse.node.v1.Line
	0,  // 1: warehouse.node.v1.PutAwayRequest.line:type_name -> warehouse.node.v1.Line
	0,  // 2: warehouse.node.v1.PickRequest.line:type_name -> warehouse.node.v1.Line
	0,  // 3: warehouse.node.v1.ReserveRequest.line:type_name -> warehouse.node.v1.Line
	0,  // 4: warehouse.node.v1.CountLineRequest.line:type_name -> warehouse.node.v1.Line
	0,  // 5: warehouse.node.v1.DispatchTransferRequest.lines:type_name -> warehouse.node.v1.Line
	0,  // 6: warehouse.node.v1.ReceiveTransferRequest.lines:type_name -> warehouse.node.v1.Line
	13, // 7: warehouse.node.v1.StockOnHandResponse.rows:type_name -> warehouse.node.v1.StockRow
	21, // 8: warehouse.node.v1.ExceptionRow.recorded_at:type_name -> google.protobuf.Timestamp
	16, // 9: warehouse.node.v1.ExceptionsResponse.rows:type_name -> warehouse.node.v1.ExceptionRow
	21, // 10: warehouse.node.v1.TransferRow.dispatched_at:type_name -> google.protobuf.Timestamp
	19, // 11: warehouse.node.v1.TransfersResponse.rows:type_name -> warehouse.node.v1.TransferRow
	2,  // 12: warehouse.node.v1.NodeAPI.Receive:input_type -> warehouse.node.v1.ReceiveRequest
	3,  // 13: warehouse.node.v1.NodeAPI.PutAway:input_type -> warehouse.node.v1.PutAwayRequest
	4,  // 14: warehouse.node.v1.NodeAPI.Pick:input_type -> warehouse.node.v1.PickRequest
	5,  // 15: warehouse.node.v1.NodeAPI.Reserve:input_type -> warehouse.node.v1.ReserveRequest
	6,  // 16: warehouse.node.v1.NodeAPI.ReleaseReservation:input_type -> warehouse.node.v1.ReleaseReservationRequest
	7,  // 17: warehouse.node.v1.NodeAPI.StartCount:input_type -> warehouse.node.v1.StartCountRequest
	8,  // 18: warehouse.node.v1.NodeAPI.CountLine:input_type -> warehouse.node.v1.CountLineRequest
	9,  // 19: warehouse.node.v1.NodeAPI.CloseCount:input_type -> warehouse.node.v1.CloseCountRequest
	10, // 20: warehouse.node.v1.NodeAPI.DispatchTransfer:input_type -> warehouse.node.v1.DispatchTransferRequest
	11, // 21: warehouse.node.v1.NodeAPI.ReceiveTransfer:input_type -> warehouse.node.v1.ReceiveTransferRequest
	12, // 22: warehouse.node.v1.NodeAPI.StockOnHand:input_type -> warehouse.node.v1.StockOnHandRequest
	15, // 23: warehouse.node.v1.NodeAPI.Exceptions:input_type -> warehouse.node.v1.ExceptionsRequest
	18, // 24: warehouse.node.v1.NodeAPI.Transfers:input_type -> warehouse.node.v1.TransfersRequest
	1,  // 25: warehouse.node.v1.NodeAPI.Receive:output_type -> warehouse.node.v1.CommandResponse
	1,  // 26: warehouse.node.v1.NodeAPI.PutAway:output_type -> warehouse.node.v1.CommandResponse
	1,  // 27: warehouse.node.v1.NodeAPI.Pick:output_type -> warehouse.node.v1.CommandResponse
	1,  // 28: warehouse.node.v1.NodeAPI.Reserve:output_type -> warehouse.node.v1.CommandResponse
	1,  // 29: warehouse.node.v1.NodeAPI.ReleaseReservation:output_type -> warehouse.node.v1.CommandResponse
	1,  // 30: warehouse.node.v1.NodeAPI.StartCount:output_type -> warehouse.node.v1.CommandResponse
	1,  // 31: warehouse.node.v1.NodeAPI.CountLine:output_type -> warehouse.node.v1.CommandResponse
	1,  // 32: warehouse.node.v1.NodeAPI.CloseCount:output_type -> warehouse.node.v1.CommandResponse
	1,  // 33: warehouse.node.v1.NodeAPI.DispatchTransfer:output_type -> warehouse.node.v1.CommandResponse
	1,  // 34: warehouse.node.v1.NodeAPI.ReceiveTransfer:output_type -> warehouse.node.v1.CommandResponse
	14, // 35: warehouse.node.v1.NodeAPI.StockOnHand:output_type -> warehouse.node.v1.StockOnHandResponse
	17, // 36: warehouse.node.v1.NodeAPI.Exceptions:output_type -> warehouse.node.v1.ExceptionsResponse
	20, // 37: warehouse.node.v1.NodeAPI.Transfers:output_type -> warehouse.node.v1.TransfersResponse
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_node_api_proto_init() }
func file_proto_node_api_proto_init() {
	if File_proto_node_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_api_proto_rawDesc), len(file_proto_node_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_api_proto_goTypes,
		DependencyIndexes: file_proto_node_api_proto_depIdxs,
		MessageInfos:      file_proto_node_api_proto_msgTypes,
	}.Build()
	File_proto_node_api_proto = out.File
	file_proto_node_api_proto_goTypes = nil
	file_proto_node_api_proto_depIdxs = nil
}
