// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/node_api.proto

package nodeapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAPI_Receive_FullMethodName            = "/warehouse.node.v1.NodeAPI/Receive"
	NodeAPI_PutAway_FullMethodName            = "/warehouse.node.v1.NodeAPI/PutAway"
	NodeAPI_Pick_FullMethodName               = "/warehouse.node.v1.NodeAPI/Pick"
	NodeAPI_Reserve_FullMethodName            = "/warehouse.node.v1.NodeAPI/Reserve"
	NodeAPI_ReleaseReservation_FullMethodName = "/warehouse.node.v1.NodeAPI/ReleaseReservation"
	NodeAPI_StartCount_FullMethodName         = "/warehouse.node.v1.NodeAPI/StartCount"
	NodeAPI_CountLine_FullMethodName          = "/warehouse.node.v1.NodeAPI/CountLine"
	NodeAPI_CloseCount_FullMethodName         = "/warehouse.node.v1.NodeAPI/CloseCount"
	NodeAPI_DispatchTransfer_FullMethodName   = "/warehouse.node.v1.NodeAPI/DispatchTransfer"
	NodeAPI_ReceiveTransfer_FullMethodName    = "/warehouse.node.v1.NodeAPI/ReceiveTransfer"
	NodeAPI_StockOnHand_FullMethodName        = "/warehouse.node.v1.NodeAPI/StockOnHand"
	NodeAPI_Exceptions_FullMethodName         = "/warehouse.node.v1.NodeAPI/Exceptions"
	NodeAPI_Transfers_FullMethodName          = "/warehouse.node.v1.NodeAPI/Transfers"
)

// NodeAPIClient is the client API for NodeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeAPI is the operator-facing service. Every command is answered from local
// state; none of them waits on central.
type NodeAPIClient interface {
	Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	PutAway(ctx context.Context, in *PutAwayRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	Pick(ctx context.Context, in *PickRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	ReleaseReservation(ctx context.Context, in *ReleaseReservationRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	StartCount(ctx context.Context, in *StartCountRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	CountLine(ctx context.Context, in *CountLineRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	CloseCount(ctx context.Context, in *CloseCountRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	DispatchTransfer(ctx context.Context, in *DispatchTransferRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	ReceiveTransfer(ctx context.Context, in *ReceiveTransferRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	StockOnHand(ctx context.Context, in *StockOnHandRequest, opts ...grpc.CallOption) (*StockOnHandResponse, error)
	Exceptions(ctx context.Context, in *ExceptionsRequest, opts ...grpc.CallOption) (*ExceptionsResponse, error)
	Transfers(ctx context.Context, in *TransfersRequest, opts ...grpc.CallOption) (*TransfersResponse, error)
}

type nodeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAPIClient(cc grpc.ClientConnInterface) NodeAPIClient {
	return &nodeAPIClient{cc}
}

func (c *nodeAPIClient) Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_Receive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) PutAway(ctx context.Context, in *PutAwayRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_PutAway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) Pick(ctx context.Context, in *PickRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_Pick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) ReleaseReservation(ctx context.Context, in *ReleaseReservationRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_ReleaseReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) StartCount(ctx context.Context, in *StartCountRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_StartCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) CountLine(ctx context.Context, in *CountLineRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_CountLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) CloseCount(ctx context.Context, in *CloseCountRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_CloseCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) DispatchTransfer(ctx context.Context, in *DispatchTransferRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_DispatchTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) ReceiveTransfer(ctx context.Context, in *ReceiveTransferRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_ReceiveTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) StockOnHand(ctx context.Context, in *StockOnHandRequest, opts ...grpc.CallOption) (*StockOnHandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockOnHandResponse)
	err := c.cc.Invoke(ctx, NodeAPI_StockOnHand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) Exceptions(ctx context.Context, in *ExceptionsRequest, opts ...grpc.CallOption) (*ExceptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExceptionsResponse)
	err := c.cc.Invoke(ctx, NodeAPI_Exceptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAPIClient) Transfers(ctx context.Context, in *TransfersRequest, opts ...grpc.CallOption) (*TransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransfersResponse)
	err := c.cc.Invoke(ctx, NodeAPI_Transfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAPIServer is the server API for NodeAPI service.
// All implementations must embed UnimplementedNodeAPIServer
// for forward compatibility.
//
// NodeAPI is the operator-facing service. Every command is answered from local
// state; none of them waits on central.
type NodeAPIServer interface {
	Receive(context.Context, *ReceiveRequest) (*CommandResponse, error)
	PutAway(context.Context, *PutAwayRequest) (*CommandResponse, error)
	Pick(context.Context, *PickRequest) (*CommandResponse, error)
	Reserve(context.Context, *ReserveRequest) (*CommandResponse, error)
	ReleaseReservation(context.Context, *ReleaseReservationRequest) (*CommandResponse, error)
	StartCount(context.Context, *StartCountRequest) (*CommandResponse, error)
	CountLine(context.Context, *CountLineRequest) (*CommandResponse, error)
	CloseCount(context.Context, *CloseCountRequest) (*CommandResponse, error)
	DispatchTransfer(context.Context, *DispatchTransferRequest) (*CommandResponse, error)
	ReceiveTransfer(context.Context, *ReceiveTransferRequest) (*CommandResponse, error)
	StockOnHand(context.Context, *StockOnHandRequest) (*StockOnHandResponse, error)
	Exceptions(context.Context, *ExceptionsRequest) (*ExceptionsResponse, error)
	Transfers(context.Context, *TransfersRequest) (*TransfersResponse, error)
	mustEmbedUnimplementedNodeAPIServer()
}

// UnimplementedNodeAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAPIServer struct{}

func (UnimplementedNodeAPIServer) Receive(context.Context, *ReceiveRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedNodeAPIServer) PutAway(context.Context, *PutAwayRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutAway not implemented")
}
func (UnimplementedNodeAPIServer) Pick(context.Context, *PickRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pick not implemented")
}
func (UnimplementedNodeAPIServer) Reserve(context.Context, *ReserveRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedNodeAPIServer) ReleaseReservation(context.Context, *ReleaseReservationRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseReservation not implemented")
}
func (UnimplementedNodeAPIServer) StartCount(context.Context, *StartCountRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCount not implemented")
}
func (UnimplementedNodeAPIServer) CountLine(context.Context, *CountLineRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountLine not implemented")
}
func (UnimplementedNodeAPIServer) CloseCount(context.Context, *CloseCountRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseCount not implemented")
}
func (UnimplementedNodeAPIServer) DispatchTransfer(context.Context, *DispatchTransferRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTransfer not implemented")
}
func (UnimplementedNodeAPIServer) ReceiveTransfer(context.Context, *ReceiveTransferRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveTransfer not implemented")
}
func (UnimplementedNodeAPIServer) StockOnHand(context.Context, *StockOnHandRequest) (*StockOnHandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StockOnHand not implemented")
}
func (UnimplementedNodeAPIServer) Exceptions(context.Context, *ExceptionsRequest) (*ExceptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exceptions not implemented")
}
func (UnimplementedNodeAPIServer) Transfers(context.Context, *TransfersRequest) (*TransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfers not implemented")
}
func (UnimplementedNodeAPIServer) mustEmbedUnimplementedNodeAPIServer() {}
func (UnimplementedNodeAPIServer) testEmbeddedByValue()                 {}

// UnsafeNodeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAPIServer will
// result in compilation errors.
type UnsafeNodeAPIServer interface {
	mustEmbedUnimplementedNodeAPIServer()
}

func RegisterNodeAPIServer(s grpc.ServiceRegistrar, srv NodeAPIServer) {
	// If the following call panics, it indicates UnimplementedNodeAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAPI_ServiceDesc, srv)
}

func _NodeAPI_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_Receive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).Receive(ctx, req.(*ReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_PutAway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAwayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).PutAway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_PutAway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).PutAway(ctx, req.(*PutAwayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_Pick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).Pick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_Pick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).Pick(ctx, req.(*PickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_ReleaseReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).ReleaseReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_ReleaseReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).ReleaseReservation(ctx, req.(*ReleaseReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_StartCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).StartCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_StartCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).StartCount(ctx, req.(*StartCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_CountLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).CountLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_CountLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).CountLine(ctx, req.(*CountLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_CloseCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).CloseCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_CloseCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).CloseCount(ctx, req.(*CloseCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_DispatchTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).DispatchTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_DispatchTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).DispatchTransfer(ctx, req.(*DispatchTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_ReceiveTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).ReceiveTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_ReceiveTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).ReceiveTransfer(ctx, req.(*ReceiveTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_StockOnHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockOnHandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).StockOnHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_StockOnHand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).StockOnHand(ctx, req.(*StockOnHandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_Exceptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExceptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).Exceptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_Exceptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).Exceptions(ctx, req.(*ExceptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAPI_Transfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAPIServer).Transfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAPI_Transfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAPIServer).Transfers(ctx, req.(*TransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAPI_ServiceDesc is the grpc.ServiceDesc for NodeAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse.node.v1.NodeAPI",
	HandlerType: (*NodeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _NodeAPI_Receive_Handler,
		},
		{
			MethodName: "PutAway",
			Handler:    _NodeAPI_PutAway_Handler,
		},
		{
			MethodName: "Pick",
			Handler:    _NodeAPI_Pick_Handler,
		},
		{
			MethodName: "Reserve",
			Handler:    _NodeAPI_Reserve_Handler,
		},
		{
			MethodName: "ReleaseReservation",
			Handler:    _NodeAPI_ReleaseReservation_Handler,
		},
		{
			MethodName: "StartCount",
			Handler:    _NodeAPI_StartCount_Handler,
		},
		{
			MethodName: "CountLine",
			Handler:    _NodeAPI_CountLine_Handler,
		},
		{
			MethodName: "CloseCount",
			Handler:    _NodeAPI_CloseCount_Handler,
		},
		{
			MethodName: "DispatchTransfer",
			Handler:    _NodeAPI_DispatchTransfer_Handler,
		},
		{
			MethodName: "ReceiveTransfer",
			Handler:    _NodeAPI_ReceiveTransfer_Handler,
		},
		{
			MethodName: "StockOnHand",
			Handler:    _NodeAPI_StockOnHand_Handler,
		},
		{
			MethodName: "Exceptions",
			Handler:    _NodeAPI_Exceptions_Handler,
		},
		{
			MethodName: "Transfers",
			Handler:    _NodeAPI_Transfers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/node_api.proto",
}
