// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: transport/grpc/node.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_transport_grpc_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_transport_grpc_node_proto_rawDescGZIP(), []int{0}
}

type ReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Qty           int64                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_transport_grpc_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_node_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ReceiveRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ReceiveRequest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type IssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Qty           int64                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRequest) Reset() {
	*x = IssueRequest{}
	mi := &file_transport_grpc_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRequest) ProtoMessage() {}

func (x *IssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRequest.ProtoReflect.Descriptor instead.
func (*IssueRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_node_proto_rawDescGZIP(), []int{2}
}

func (x *IssueRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *IssueRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *IssueRequest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Qty           int64                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_transport_grpc_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_node_proto_rawDescGZIP(), []int{3}
}

func (x *MoveRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *MoveRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MoveRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MoveRequest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_transport_grpc_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_node_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *BalanceRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qty           int64                  `protobuf:"varint,1,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_transport_grpc_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_node_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceResponse) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type BalanceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Qty           int64                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceEntry) Reset() {
	*x = BalanceEntry{}
	mi := &file_transport_grpc_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceEntry) ProtoMessage() {}

func (x *BalanceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceEntry.ProtoReflect.Descriptor instead.
func (*BalanceEntry) Descriptor() ([]byte, []int) {
	return file_transport_grpc_node_proto_rawDescGZIP(), []int{6}
}

func (x *BalanceEntry) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *BalanceEntry) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BalanceEntry) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type BalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*BalanceEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalancesResponse) Reset() {
	*x = BalancesResponse{}
	mi := &file_transport_grpc_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancesResponse) ProtoMessage() {}

func (x *BalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancesResponse.ProtoReflect.Descriptor instead.
func (*BalancesResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_node_proto_rawDescGZIP(), []int{7}
}

func (x *BalancesResponse) GetEntries() []*BalanceEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_transport_grpc_node_proto protoreflect.FileDescriptor

const file_transport_grpc_node_proto_rawDesc = "" +
	"\n" +
	"\x19transport/grpc/node.proto\x12\x12localfirst.node.v1\"\a\n" +
	"\x05Empty\"P\n" +
	"\x0eReceiveRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x03R\x03qty\"N\n" +
	"\fIssueRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x03R\x03qty\"U\n" +
	"\vMoveRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x03R\x03qty\">\n" +
	"\x0eBalanceRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"#\n" +
	"\x0fBalanceResponse\x12\x10\n" +
	"\x03qty\x18\x01 \x01(\x03R\x03qty\"N\n" +
	"\fBalanceEntry\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x03R\x03qty\"N\n" +
	"\x10BalancesResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .localfirst.node.v1.BalanceEntryR\aentries2\xfb\x02\n" +
	"\x04Node\x12H\n" +
	"\aReceive\x12\".localfirst.node.v1.ReceiveRequest\x1a\x19.localfirst.node.v1.Empty\x12D\n" +
	"\x05Issue\x12 .localfirst.node.v1.IssueRequest\x1a\x19.localfirst.node.v1.Empty\x12B\n" +
	"\x04Move\x12\x1f.localfirst.node.v1.MoveRequest\x1a\x19.localfirst.node.v1.Empty\x12R\n" +
	"\aBalance\x12\".localfirst.node.v1.BalanceRequest\x1a#.localfirst.node.v1.BalanceResponse\x12K\n" +
	"\bBalances\x12\x19.localfirst.node.v1.Empty\x1a$.localfirst.node.v1.BalancesResponseBUZSgithub.com/dhiazfathra/local-first-architecture/localfirst-go/transport/grpc/nodepbb\x06proto3"

var (
	file_transport_grpc_node_proto_rawDescOnce sync.Once
	file_transport_grpc_node_proto_rawDescData []byte
)

func file_transport_grpc_node_proto_rawDescGZIP() []byte {
	file_transport_grpc_node_proto_rawDescOnce.Do(func() {
		file_transport_grpc_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_grpc_node_proto_rawDesc), len(file_transport_grpc_node_proto_rawDesc)))
	})
	return file_transport_grpc_node_proto_rawDescData
}

var file_transport_grpc_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_transport_grpc_node_proto_goTypes = []any{
	(*Empty)(nil),            // 0: localfirst.node.v1.Empty
	(*ReceiveRequest)(nil),   // 1: localfirst.node.v1.ReceiveRequest
	(*IssueRequest)(nil),     // 2: localfirst.node.v1.IssueRequest
	(*MoveRequest)(nil),      // 3: localfirst.node.v1.MoveRequest
	(*BalanceRequest)(nil),   // 4: localfirst.node.v1.BalanceRequest
	(*BalanceResponse)(nil),  // 5: localfirst.node.v1.BalanceResponse
	(*BalanceEntry)(nil),     // 6: localfirst.node.v1.BalanceEntry
	(*BalancesResponse)(nil), // 7: localfirst.node.v1.BalancesResponse
}
var file_transport_grpc_node_proto_depIdxs = []int32{
	6, // 0: localfirst.node.v1.BalancesResponse.entries:type_name -> localfirst.node.v1.BalanceEntry
	1, // 1: localfirst.node.v1.Node.Receive:input_type -> localfirst.node.v1.ReceiveRequest
	2, // 2: localfirst.node.v1.Node.Issue:input_type -> localfirst.node.v1.IssueRequest
	3, // 3: localfirst.node.v1.Node.Move:input_type -> localfirst.node.v1.MoveRequest
	4, // 4: localfirst.node.v1.Node.Balance:input_type -> localfirst.node.v1.BalanceRequest
	0, // 5: localfirst.node.v1.Node.Balances:input_type -> localfirst.node.v1.Empty
	0, // 6: localfirst.node.v1.Node.Receive:output_type -> localfirst.node.v1.Empty
	0, // 7: localfirst.node.v1.Node.Issue:output_type -> localfirst.node.v1.Empty
	0, // 8: localfirst.node.v1.Node.Move:output_type -> localfirst.node.v1.Empty
	5, // 9: localfirst.node.v1.Node.Balance:output_type -> localfirst.node.v1.BalanceResponse
	7, // 10: localfirst.node.v1.Node.Balances:output_type -> localfirst.node.v1.BalancesResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transport_grpc_node_proto_init() }
func file_transport_grpc_node_proto_init() {
	if File_transport_grpc_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_grpc_node_proto_rawDesc), len(file_transport_grpc_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_node_proto_goTypes,
		DependencyIndexes: file_transport_grpc_node_proto_depIdxs,
		MessageInfos:      file_transport_grpc_node_proto_msgTypes,
	}.Build()
	File_transport_grpc_node_proto = out.File
	file_transport_grpc_node_proto_goTypes = nil
	file_transport_grpc_node_proto_depIdxs = nil
}
