// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sync.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_Events
	//	*ClientFrame_Ack
	Body          isClientFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetBody() isClientFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetEvents() *Events {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *ClientFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isClientFrame_Body interface {
	isClientFrame_Body()
}

type ClientFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // my node id + my version vector
}

type ClientFrame_Events struct {
	Events *Events `protobuf:"bytes,2,opt,name=events,proto3,oneof"` // batch of my events the peer lacks
}

type ClientFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"` // version vector after applying peer's batch
}

func (*ClientFrame_Hello) isClientFrame_Body() {}

func (*ClientFrame_Events) isClientFrame_Body() {}

func (*ClientFrame_Ack) isClientFrame_Body() {}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Welcome
	//	*ServerFrame_Events
	//	*ServerFrame_Ack
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerFrame) GetEvents() *Events {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *ServerFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"` // central's version vector
}

type ServerFrame_Events struct {
	Events *Events `protobuf:"bytes,2,opt,name=events,proto3,oneof"`
}

type ServerFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*ServerFrame_Welcome) isServerFrame_Body() {}

func (*ServerFrame_Events) isServerFrame_Body() {}

func (*ServerFrame_Ack) isServerFrame_Body() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VersionVector map[string]uint64      `protobuf:"bytes,2,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetVersionVector() map[string]uint64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VersionVector map[string]uint64      `protobuf:"bytes,2,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Welcome) GetVersionVector() map[string]uint64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *Events) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionVector map[string]uint64      `protobuf:"bytes,1,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetVersionVector() map[string]uint64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	HlcWall       int64                  `protobuf:"varint,3,opt,name=hlc_wall,json=hlcWall,proto3" json:"hlc_wall,omitempty"`
	HlcLogical    uint32                 `protobuf:"varint,4,opt,name=hlc_logical,json=hlcLogical,proto3" json:"hlc_logical,omitempty"`
	Sku           string                 `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	Kind          int32                  `protobuf:"varint,6,opt,name=kind,proto3" json:"kind,omitempty"`
	Delta         int64                  `protobuf:"varint,7,opt,name=delta,proto3" json:"delta,omitempty"`                                         // kind == 1 only
	Name          *string                `protobuf:"bytes,8,opt,name=name,proto3,oneof" json:"name,omitempty"`                                      // kind == 2 only
	ReorderPoint  *int64                 `protobuf:"varint,9,opt,name=reorder_point,json=reorderPoint,proto3,oneof" json:"reorder_point,omitempty"` // kind == 2 only
	DeletedTo     *bool                  `protobuf:"varint,10,opt,name=deleted_to,json=deletedTo,proto3,oneof" json:"deleted_to,omitempty"`         // kind == 3 only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetHlcWall() int64 {
	if x != nil {
		return x.HlcWall
	}
	return 0
}

func (x *Event) GetHlcLogical() uint32 {
	if x != nil {
		return x.HlcLogical
	}
	return 0
}

func (x *Event) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Event) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Event) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Event) GetReorderPoint() int64 {
	if x != nil && x.ReorderPoint != nil {
		return *x.ReorderPoint
	}
	return 0
}

func (x *Event) GetDeletedTo() bool {
	if x != nil && x.DeletedTo != nil {
		return *x.DeletedTo
	}
	return false
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\x13eventloglab.sync.v1\"\xae\x01\n" +
	"\vClientFrame\x122\n" +
	"\x05hello\x18\x01 \x01(\v2\x1a.eventloglab.sync.v1.HelloH\x00R\x05hello\x125\n" +
	"\x06events\x18\x02 \x01(\v2\x1b.eventloglab.sync.v1.EventsH\x00R\x06events\x12,\n" +
	"\x03ack\x18\x03 \x01(\v2\x18.eventloglab.sync.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04body\"\xb4\x01\n" +
	"\vServerFrame\x128\n" +
	"\awelcome\x18\x01 \x01(\v2\x1c.eventloglab.sync.v1.WelcomeH\x00R\awelcome\x125\n" +
	"\x06events\x18\x02 \x01(\v2\x1b.eventloglab.sync.v1.EventsH\x00R\x06events\x12,\n" +
	"\x03ack\x18\x03 \x01(\v2\x18.eventloglab.sync.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04body\"\xb8\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12T\n" +
	"\x0eversion_vector\x18\x02 \x03(\v2-.eventloglab.sync.v1.Hello.VersionVectorEntryR\rversionVector\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xbc\x01\n" +
	"\aWelcome\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12V\n" +
	"\x0eversion_vector\x18\x02 \x03(\v2/.eventloglab.sync.v1.Welcome.VersionVectorEntryR\rversionVector\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"<\n" +
	"\x06Events\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.eventloglab.sync.v1.EventR\x06events\"\x9b\x01\n" +
	"\x03Ack\x12R\n" +
	"\x0eversion_vector\x18\x01 \x03(\v2+.eventloglab.sync.v1.Ack.VersionVectorEntryR\rversionVector\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xbb\x02\n" +
	"\x05Event\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x19\n" +
	"\bhlc_wall\x18\x03 \x01(\x03R\ahlcWall\x12\x1f\n" +
	"\vhlc_logical\x18\x04 \x01(\rR\n" +
	"hlcLogical\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\x05R\x04kind\x12\x14\n" +
	"\x05delta\x18\a \x01(\x03R\x05delta\x12\x17\n" +
	"\x04name\x18\b \x01(\tH\x00R\x04name\x88\x01\x01\x12(\n" +
	"\rreorder_point\x18\t \x01(\x03H\x01R\freorderPoint\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_to\x18\n" +
	" \x01(\bH\x02R\tdeletedTo\x88\x01\x01B\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_reorder_pointB\r\n" +
	"\v_deleted_to2[\n" +
	"\x04Sync\x12S\n" +
	"\tReplicate\x12 .eventloglab.sync.v1.ClientFrame\x1a .eventloglab.sync.v1.ServerFrame(\x010\x01BJZHgithub.com/dhiazfathra/local-first-architecture/eventlog-lab/sync/syncpbb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sync_proto_goTypes = []any{
	(*ClientFrame)(nil), // 0: eventloglab.sync.v1.ClientFrame
	(*ServerFrame)(nil), // 1: eventloglab.sync.v1.ServerFrame
	(*Hello)(nil),       // 2: eventloglab.sync.v1.Hello
	(*Welcome)(nil),     // 3: eventloglab.sync.v1.Welcome
	(*Events)(nil),      // 4: eventloglab.sync.v1.Events
	(*Ack)(nil),         // 5: eventloglab.sync.v1.Ack
	(*Event)(nil),       // 6: eventloglab.sync.v1.Event
	nil,                 // 7: eventloglab.sync.v1.Hello.VersionVectorEntry
	nil,                 // 8: eventloglab.sync.v1.Welcome.VersionVectorEntry
	nil,                 // 9: eventloglab.sync.v1.Ack.VersionVectorEntry
}
var file_sync_proto_depIdxs = []int32{
	2,  // 0: eventloglab.sync.v1.ClientFrame.hello:type_name -> eventloglab.sync.v1.Hello
	4,  // 1: eventloglab.sync.v1.ClientFrame.events:type_name -> eventloglab.sync.v1.Events
	5,  // 2: eventloglab.sync.v1.ClientFrame.ack:type_name -> eventloglab.sync.v1.Ack
	3,  // 3: eventloglab.sync.v1.ServerFrame.welcome:type_name -> eventloglab.sync.v1.Welcome
	4,  // 4: eventloglab.sync.v1.ServerFrame.events:type_name -> eventloglab.sync.v1.Events
	5,  // 5: eventloglab.sync.v1.ServerFrame.ack:type_name -> eventloglab.sync.v1.Ack
	7,  // 6: eventloglab.sync.v1.Hello.version_vector:type_name -> eventloglab.sync.v1.Hello.VersionVectorEntry
	8,  // 7: eventloglab.sync.v1.Welcome.version_vector:type_name -> eventloglab.sync.v1.Welcome.VersionVectorEntry
	6,  // 8: eventloglab.sync.v1.Events.events:type_name -> eventloglab.sync.v1.Event
	9,  // 9: eventloglab.sync.v1.Ack.version_vector:type_name -> eventloglab.sync.v1.Ack.VersionVectorEntry
	0,  // 10: eventloglab.sync.v1.Sync.Replicate:input_type -> eventloglab.sync.v1.ClientFrame
	1,  // 11: eventloglab.sync.v1.Sync.Replicate:output_type -> eventloglab.sync.v1.ServerFrame
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_Events)(nil),
		(*ClientFrame_Ack)(nil),
	}
	file_sync_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_Welcome)(nil),
		(*ServerFrame_Events)(nil),
		(*ServerFrame_Ack)(nil),
	}
	file_sync_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
