// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/warehouse/sync/v1/sync.proto

package syncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sync_Replicate_FullMethodName = "/warehouse.sync.v1.Sync/Replicate"
)

// SyncClient is the client API for Sync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sync replicates events in both directions over one stream. The node always opens
// it, because the node may be behind a connection central cannot dial.
type SyncClient interface {
	Replicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeFrame, CentralFrame], error)
}

type syncClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncClient(cc grpc.ClientConnInterface) SyncClient {
	return &syncClient{cc}
}

func (c *syncClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeFrame, CentralFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sync_ServiceDesc.Streams[0], Sync_Replicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeFrame, CentralFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sync_ReplicateClient = grpc.BidiStreamingClient[NodeFrame, CentralFrame]

// SyncServer is the server API for Sync service.
// All implementations must embed UnimplementedSyncServer
// for forward compatibility.
//
// Sync replicates events in both directions over one stream. The node always opens
// it, because the node may be behind a connection central cannot dial.
type SyncServer interface {
	Replicate(grpc.BidiStreamingServer[NodeFrame, CentralFrame]) error
	mustEmbedUnimplementedSyncServer()
}

// UnimplementedSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServer struct{}

func (UnimplementedSyncServer) Replicate(grpc.BidiStreamingServer[NodeFrame, CentralFrame]) error {
	return status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedSyncServer) mustEmbedUnimplementedSyncServer() {}
func (UnimplementedSyncServer) testEmbeddedByValue()              {}

// UnsafeSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServer will
// result in compilation errors.
type UnsafeSyncServer interface {
	mustEmbedUnimplementedSyncServer()
}

func RegisterSyncServer(s grpc.ServiceRegistrar, srv SyncServer) {
	// If the following call panics, it indicates UnimplementedSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sync_ServiceDesc, srv)
}

func _Sync_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServer).Replicate(&grpc.GenericServerStream[NodeFrame, CentralFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sync_ReplicateServer = grpc.BidiStreamingServer[NodeFrame, CentralFrame]

// Sync_ServiceDesc is the grpc.ServiceDesc for Sync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warehouse.sync.v1.Sync",
	HandlerType: (*SyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Replicate",
			Handler:       _Sync_Replicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/warehouse/sync/v1/sync.proto",
}
