// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/sync.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventID is an event's global identity: the node that produced it and that node's
// own monotonic sequence number.
type EventID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventID) Reset() {
	*x = EventID{}
	mi := &file_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventID) ProtoMessage() {}

func (x *EventID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventID.ProtoReflect.Descriptor instead.
func (*EventID) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{0}
}

func (x *EventID) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EventID) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// HLC is a hybrid logical clock reading. It orders events across nodes without
// requiring their wall clocks to agree.
type HLC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wall          int64                  `protobuf:"varint,1,opt,name=wall,proto3" json:"wall,omitempty"`
	Counter       uint32                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLC) Reset() {
	*x = HLC{}
	mi := &file_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLC) ProtoMessage() {}

func (x *HLC) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLC.ProtoReflect.Descriptor instead.
func (*HLC) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{1}
}

func (x *HLC) GetWall() int64 {
	if x != nil {
		return x.Wall
	}
	return 0
}

func (x *HLC) GetCounter() uint32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *HLC) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

// Event is one envelope on the wire. causation_id is set only on compensating events
// emitted by central, and names the event being compensated.
type Event struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 *EventID               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AggregateId        string                 `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	Type               string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Hlc                *HLC                   `protobuf:"bytes,4,opt,name=hlc,proto3" json:"hlc,omitempty"`
	RecordedAtUnixNano int64                  `protobuf:"varint,5,opt,name=recorded_at_unix_nano,json=recordedAtUnixNano,proto3" json:"recorded_at_unix_nano,omitempty"`
	CausationId        *EventID               `protobuf:"bytes,6,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	Payload            []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() *EventID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Event) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetHlc() *HLC {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *Event) GetRecordedAtUnixNano() int64 {
	if x != nil {
		return x.RecordedAtUnixNano
	}
	return 0
}

func (x *Event) GetCausationId() *EventID {
	if x != nil {
		return x.CausationId
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// EventBatch is one bounded chunk. more is true when the sender has further events
// ready, which lets the receiver keep asking without guessing. last_ord is set only
// on batches central sends down, and is the outbound position of the final event in
// the batch — what the node acknowledges and persists as its pull cursor.
type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	More          bool                   `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	LastOrd       uint64                 `protobuf:"varint,3,opt,name=last_ord,json=lastOrd,proto3" json:"last_ord,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_proto_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{3}
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

func (x *EventBatch) GetLastOrd() uint64 {
	if x != nil {
		return x.LastOrd
	}
	return 0
}

// Hello opens a session. version_vector is the highest sequence the node holds per
// originating node, so central can tell what it still needs to send.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VersionVector map[string]uint64      `protobuf:"bytes,2,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PulledCursor  uint64                 `protobuf:"varint,3,opt,name=pulled_cursor,json=pulledCursor,proto3" json:"pulled_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetVersionVector() map[string]uint64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *Hello) GetPulledCursor() uint64 {
	if x != nil {
		return x.PulledCursor
	}
	return 0
}

// Welcome answers Hello with the highest sequence central holds for this node, so
// the node knows where to resume pushing from.
type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnownSeq      uint64                 `protobuf:"varint,1,opt,name=known_seq,json=knownSeq,proto3" json:"known_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_proto_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{5}
}

func (x *Welcome) GetKnownSeq() uint64 {
	if x != nil {
		return x.KnownSeq
	}
	return 0
}

// Ack confirms durability. seq is the highest sequence of the node's own events that
// central has persisted; ord is the highest downstream position the node has applied.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ord           uint64                 `protobuf:"varint,2,opt,name=ord,proto3" json:"ord,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Ack) GetOrd() uint64 {
	if x != nil {
		return x.Ord
	}
	return 0
}

type NodeFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*NodeFrame_Hello
	//	*NodeFrame_Events
	//	*NodeFrame_Ack
	Body          isNodeFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeFrame) Reset() {
	*x = NodeFrame{}
	mi := &file_proto_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeFrame) ProtoMessage() {}

func (x *NodeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeFrame.ProtoReflect.Descriptor instead.
func (*NodeFrame) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{7}
}

func (x *NodeFrame) GetBody() isNodeFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*NodeFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *NodeFrame) GetEvents() *EventBatch {
	if x != nil {
		if x, ok := x.Body.(*NodeFrame_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *NodeFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*NodeFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isNodeFrame_Body interface {
	isNodeFrame_Body()
}

type NodeFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type NodeFrame_Events struct {
	Events *EventBatch `protobuf:"bytes,2,opt,name=events,proto3,oneof"`
}

type NodeFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*NodeFrame_Hello) isNodeFrame_Body() {}

func (*NodeFrame_Events) isNodeFrame_Body() {}

func (*NodeFrame_Ack) isNodeFrame_Body() {}

type CentralFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*CentralFrame_Welcome
	//	*CentralFrame_Events
	//	*CentralFrame_Ack
	Body          isCentralFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CentralFrame) Reset() {
	*x = CentralFrame{}
	mi := &file_proto_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CentralFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentralFrame) ProtoMessage() {}

func (x *CentralFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentralFrame.ProtoReflect.Descriptor instead.
func (*CentralFrame) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{8}
}

func (x *CentralFrame) GetBody() isCentralFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CentralFrame) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*CentralFrame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *CentralFrame) GetEvents() *EventBatch {
	if x != nil {
		if x, ok := x.Body.(*CentralFrame_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *CentralFrame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*CentralFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isCentralFrame_Body interface {
	isCentralFrame_Body()
}

type CentralFrame_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type CentralFrame_Events struct {
	Events *EventBatch `protobuf:"bytes,2,opt,name=events,proto3,oneof"`
}

type CentralFrame_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*CentralFrame_Welcome) isCentralFrame_Body() {}

func (*CentralFrame_Events) isCentralFrame_Body() {}

func (*CentralFrame_Ack) isCentralFrame_Body() {}

var File_proto_sync_proto protoreflect.FileDescriptor

const file_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x10proto/sync.proto\x12\x11warehouse.sync.v1\"4\n" +
	"\aEventID\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"G\n" +
	"\x03HLC\x12\x12\n" +
	"\x04wall\x18\x01 \x01(\x03R\x04wall\x12\x18\n" +
	"\acounter\x18\x02 \x01(\rR\acounter\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\"\xa0\x02\n" +
	"\x05Event\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\x1a.warehouse.sync.v1.EventIDR\x02id\x12!\n" +
	"\faggregate_id\x18\x02 \x01(\tR\vaggregateId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12(\n" +
	"\x03hlc\x18\x04 \x01(\v2\x16.warehouse.sync.v1.HLCR\x03hlc\x121\n" +
	"\x15recorded_at_unix_nano\x18\x05 \x01(\x03R\x12recordedAtUnixNano\x12=\n" +
	"\fcausation_id\x18\x06 \x01(\v2\x1a.warehouse.sync.v1.EventIDR\vcausationId\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"m\n" +
	"\n" +
	"EventBatch\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.warehouse.sync.v1.EventR\x06events\x12\x12\n" +
	"\x04more\x18\x02 \x01(\bR\x04more\x12\x19\n" +
	"\blast_ord\x18\x03 \x01(\x04R\alastOrd\"\xdb\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12R\n" +
	"\x0eversion_vector\x18\x02 \x03(\v2+.warehouse.sync.v1.Hello.VersionVectorEntryR\rversionVector\x12#\n" +
	"\rpulled_cursor\x18\x03 \x01(\x04R\fpulledCursor\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"&\n" +
	"\aWelcome\x12\x1b\n" +
	"\tknown_seq\x18\x01 \x01(\x04R\bknownSeq\")\n" +
	"\x03Ack\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03ord\x18\x02 \x01(\x04R\x03ord\"\xaa\x01\n" +
	"\tNodeFrame\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.warehouse.sync.v1.HelloH\x00R\x05hello\x127\n" +
	"\x06events\x18\x02 \x01(\v2\x1d.warehouse.sync.v1.EventBatchH\x00R\x06events\x12*\n" +
	"\x03ack\x18\x03 \x01(\v2\x16.warehouse.sync.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04body\"\xb3\x01\n" +
	"\fCentralFrame\x126\n" +
	"\awelcome\x18\x01 \x01(\v2\x1a.warehouse.sync.v1.WelcomeH\x00R\awelcome\x127\n" +
	"\x06events\x18\x02 \x01(\v2\x1d.warehouse.sync.v1.EventBatchH\x00R\x06events\x12*\n" +
	"\x03ack\x18\x03 \x01(\v2\x16.warehouse.sync.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04body2V\n" +
	"\x04Sync\x12N\n" +
	"\tReplicate\x12\x1c.warehouse.sync.v1.NodeFrame\x1a\x1f.warehouse.sync.v1.CentralFrame(\x010\x01BTZRgithub.com/dhiazfathra/local-first-architecture/warehouse-node/proto/syncpb;syncpbb\x06proto3"

var (
	file_proto_sync_proto_rawDescOnce sync.Once
	file_proto_sync_proto_rawDescData []byte
)

func file_proto_sync_proto_rawDescGZIP() []byte {
	file_proto_sync_proto_rawDescOnce.Do(func() {
		file_proto_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sync_proto_rawDesc), len(file_proto_sync_proto_rawDesc)))
	})
	return file_proto_sync_proto_rawDescData
}

var file_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_sync_proto_goTypes = []any{
	(*EventID)(nil),      // 0: warehouse.sync.v1.EventID
	(*HLC)(nil),          // 1: warehouse.sync.v1.HLC
	(*Event)(nil),        // 2: warehouse.sync.v1.Event
	(*EventBatch)(nil),   // 3: warehouse.sync.v1.EventBatch
	(*Hello)(nil),        // 4: warehouse.sync.v1.Hello
	(*Welcome)(nil),      // 5: warehouse.sync.v1.Welcome
	(*Ack)(nil),          // 6: warehouse.sync.v1.Ack
	(*NodeFrame)(nil),    // 7: warehouse.sync.v1.NodeFrame
	(*CentralFrame)(nil), // 8: warehouse.sync.v1.CentralFrame
	nil,                  // 9: warehouse.sync.v1.Hello.VersionVectorEntry
}
var file_proto_sync_proto_depIdxs = []int32{
	0,  // 0: warehouse.sync.v1.Event.id:type_name -> warehouse.sync.v1.EventID
	1,  // 1: warehouse.sync.v1.Event.hlc:type_name -> warehouse.sync.v1.HLC
	0,  // 2: warehouse.sync.v1.Event.causation_id:type_name -> warehouse.sync.v1.EventID
	2,  // 3: warehouse.sync.v1.EventBatch.events:type_name -> warehouse.sync.v1.Event
	9,  // 4: warehouse.sync.v1.Hello.version_vector:type_name -> warehouse.sync.v1.Hello.VersionVectorEntry
	4,  // 5: warehouse.sync.v1.NodeFrame.hello:type_name -> warehouse.sync.v1.Hello
	3,  // 6: warehouse.sync.v1.NodeFrame.events:type_name -> warehouse.sync.v1.EventBatch
	6,  // 7: warehouse.sync.v1.NodeFrame.ack:type_name -> warehouse.sync.v1.Ack
	5,  // 8: warehouse.sync.v1.CentralFrame.welcome:type_name -> warehouse.sync.v1.Welcome
	3,  // 9: warehouse.sync.v1.CentralFrame.events:type_name -> warehouse.sync.v1.EventBatch
	6,  // 10: warehouse.sync.v1.CentralFrame.ack:type_name -> warehouse.sync.v1.Ack
	7,  // 11: warehouse.sync.v1.Sync.Replicate:input_type -> warehouse.sync.v1.NodeFrame
	8,  // 12: warehouse.sync.v1.Sync.Replicate:output_type -> warehouse.sync.v1.CentralFrame
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_sync_proto_init() }
func file_proto_sync_proto_init() {
	if File_proto_sync_proto != nil {
		return
	}
	file_proto_sync_proto_msgTypes[7].OneofWrappers = []any{
		(*NodeFrame_Hello)(nil),
		(*NodeFrame_Events)(nil),
		(*NodeFrame_Ack)(nil),
	}
	file_proto_sync_proto_msgTypes[8].OneofWrappers = []any{
		(*CentralFrame_Welcome)(nil),
		(*CentralFrame_Events)(nil),
		(*CentralFrame_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sync_proto_rawDesc), len(file_proto_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sync_proto_goTypes,
		DependencyIndexes: file_proto_sync_proto_depIdxs,
		MessageInfos:      file_proto_sync_proto_msgTypes,
	}.Build()
	File_proto_sync_proto = out.File
	file_proto_sync_proto_goTypes = nil
	file_proto_sync_proto_depIdxs = nil
}
