// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sync/sync.proto

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_Hello
	//	*Frame_Batch
	//	*Frame_Ack
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Frame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Frame) GetBatch() *Batch {
	if x != nil {
		if x, ok := x.Body.(*Frame_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *Frame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*Frame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // node id + version vector
}

type Frame_Batch struct {
	Batch *Batch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"` // records the peer lacks
}

type Frame_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,proto3,oneof"` // version vector after apply
}

func (*Frame_Hello) isFrame_Body() {}

func (*Frame_Batch) isFrame_Body() {}

func (*Frame_Ack) isFrame_Body() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       map[string]uint64      `protobuf:"bytes,2,rep,name=version,proto3" json:"version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetVersion() map[string]uint64 {
	if x != nil {
		return x.Version
	}
	return nil
}

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_sync_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Batch) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       map[string]uint64      `protobuf:"bytes,1,rep,name=version,proto3" json:"version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_sync_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetVersion() map[string]uint64 {
	if x != nil {
		return x.Version
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	HlcWall       int64                  `protobuf:"varint,3,opt,name=hlc_wall,json=hlcWall,proto3" json:"hlc_wall,omitempty"`
	HlcLogical    uint32                 `protobuf:"varint,4,opt,name=hlc_logical,json=hlcLogical,proto3" json:"hlc_logical,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_sync_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Record) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Record) GetHlcWall() int64 {
	if x != nil {
		return x.HlcWall
	}
	return 0
}

func (x *Record) GetHlcLogical() uint32 {
	if x != nil {
		return x.HlcLogical
	}
	return 0
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Record) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_sync_sync_proto protoreflect.FileDescriptor

const file_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x0fsync/sync.proto\x12\x12localfirst.sync.v1\"\xa2\x01\n" +
	"\x05Frame\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.localfirst.sync.v1.HelloH\x00R\x05hello\x121\n" +
	"\x05batch\x18\x02 \x01(\v2\x19.localfirst.sync.v1.BatchH\x00R\x05batch\x12+\n" +
	"\x03ack\x18\x03 \x01(\v2\x17.localfirst.sync.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04body\"\x9e\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12@\n" +
	"\aversion\x18\x02 \x03(\v2&.localfirst.sync.v1.Hello.VersionEntryR\aversion\x1a:\n" +
	"\fVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"=\n" +
	"\x05Batch\x124\n" +
	"\arecords\x18\x01 \x03(\v2\x1a.localfirst.sync.v1.RecordR\arecords\"\x81\x01\n" +
	"\x03Ack\x12>\n" +
	"\aversion\x18\x01 \x03(\v2$.localfirst.sync.v1.Ack.VersionEntryR\aversion\x1a:\n" +
	"\fVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x9d\x01\n" +
	"\x06Record\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x19\n" +
	"\bhlc_wall\x18\x03 \x01(\x03R\ahlcWall\x12\x1f\n" +
	"\vhlc_logical\x18\x04 \x01(\rR\n" +
	"hlcLogical\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload2M\n" +
	"\x04Sync\x12E\n" +
	"\tReplicate\x12\x19.localfirst.sync.v1.Frame\x1a\x19.localfirst.sync.v1.Frame(\x010\x01BKZIgithub.com/dhiazfathra/local-first-architecture/localfirst-go/sync/syncpbb\x06proto3"

var (
	file_sync_sync_proto_rawDescOnce sync.Once
	file_sync_sync_proto_rawDescData []byte
)

func file_sync_sync_proto_rawDescGZIP() []byte {
	file_sync_sync_proto_rawDescOnce.Do(func() {
		file_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_sync_proto_rawDesc), len(file_sync_sync_proto_rawDesc)))
	})
	return file_sync_sync_proto_rawDescData
}

var file_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sync_sync_proto_goTypes = []any{
	(*Frame)(nil),  // 0: localfirst.sync.v1.Frame
	(*Hello)(nil),  // 1: localfirst.sync.v1.Hello
	(*Batch)(nil),  // 2: localfirst.sync.v1.Batch
	(*Ack)(nil),    // 3: localfirst.sync.v1.Ack
	(*Record)(nil), // 4: localfirst.sync.v1.Record
	nil,            // 5: localfirst.sync.v1.Hello.VersionEntry
	nil,            // 6: localfirst.sync.v1.Ack.VersionEntry
}
var file_sync_sync_proto_depIdxs = []int32{
	1, // 0: localfirst.sync.v1.Frame.hello:type_name -> localfirst.sync.v1.Hello
	2, // 1: localfirst.sync.v1.Frame.batch:type_name -> localfirst.sync.v1.Batch
	3, // 2: localfirst.sync.v1.Frame.ack:type_name -> localfirst.sync.v1.Ack
	5, // 3: localfirst.sync.v1.Hello.version:type_name -> localfirst.sync.v1.Hello.VersionEntry
	4, // 4: localfirst.sync.v1.Batch.records:type_name -> localfirst.sync.v1.Record
	6, // 5: localfirst.sync.v1.Ack.version:type_name -> localfirst.sync.v1.Ack.VersionEntry
	0, // 6: localfirst.sync.v1.Sync.Replicate:input_type -> localfirst.sync.v1.Frame
	0, // 7: localfirst.sync.v1.Sync.Replicate:output_type -> localfirst.sync.v1.Frame
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sync_sync_proto_init() }
func file_sync_sync_proto_init() {
	if File_sync_sync_proto != nil {
		return
	}
	file_sync_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Hello)(nil),
		(*Frame_Batch)(nil),
		(*Frame_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_sync_proto_rawDesc), len(file_sync_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_sync_proto_goTypes,
		DependencyIndexes: file_sync_sync_proto_depIdxs,
		MessageInfos:      file_sync_sync_proto_msgTypes,
	}.Build()
	File_sync_sync_proto = out.File
	file_sync_sync_proto_goTypes = nil
	file_sync_sync_proto_depIdxs = nil
}
